import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import type { Plugin, ResolvedConfig } from "vite";
import { resolveGlobalsCssHref, resolveHydrateEntryHref, resolveVeiOverlayHref } from "./resolve-asset-href.js";

const GENERATED_FILE_PATH = fileURLToPath(new URL("./generated-asset-hrefs.ts", import.meta.url));

/**
 * Regenerates `generated-asset-hrefs.ts` right after the CLIENT production
 * build (`vite build --outDir dist/client`) finishes, from the
 * `manifest.json` it just wrote - see that file's own doc comment for why
 * `app-router/assets.ts` needs the hrefs baked in as plain strings rather
 * than read off disk at server runtime (Cloudflare Workers has no
 * filesystem at all - `status/cloudflare-workers-adapter.md`). No-op in dev
 * (`apply: "build"`) and in the SSR build (`vite build --ssr
 * entry-node.ts`/`entry-worker.ts`), which never produces a client manifest
 * of its own - `resolveGlobalsCssHref`/`resolveHydrateEntryHref` are the
 * same pure, unit-tested functions `assets.ts` exports, just called here at
 * build time instead of (previously) at server runtime.
 */
export function assetHrefsPlugin(): Plugin {
  let config: ResolvedConfig;
  return {
    name: "drycms-asset-hrefs",
    apply: "build",
    configResolved(resolved) {
      config = resolved;
    },
    closeBundle() {
      if (config.build.ssr) return;
      const manifestPath = resolve(config.root, config.build.outDir, ".vite/manifest.json");
      const globalsHref = resolveGlobalsCssHref(false, manifestPath);
      const hydrateHref = resolveHydrateEntryHref(false, manifestPath);
      const veiOverlayHref = resolveVeiOverlayHref(false, manifestPath);
      writeFileSync(
        GENERATED_FILE_PATH,
        `// Auto-generated by \`asset-hrefs-plugin.ts\` right after \`vite build --outDir dist/client\` finishes - do not edit by hand.\n` +
          `export const GLOBALS_CSS_HREF = ${JSON.stringify(globalsHref)};\n` +
          `export const HYDRATE_ENTRY_HREF = ${JSON.stringify(hydrateHref)};\n` +
          `export const VEI_OVERLAY_HREF = ${JSON.stringify(veiOverlayHref)};\n`,
      );
    },
  };
}
