// Auto-generated by `asset-hrefs-plugin.ts` right after `vite build --outDir dist/client` finishes - do not edit by hand.
export const GLOBALS_CSS_HREF = "/assets/appsGlobals-CZTYXW6U.css";
export const HYDRATE_ENTRY_HREF = "/assets/appsHydrate-E_AI8ZhQ.js";
export const VEI_OVERLAY_HREF = "/assets/appsVeiOverlay-BEVmm97j.js";
export const HYDRATE_BUILT_HREF = "/assets/appsHydrateBuilt-CRr9R7gU.js";
export const VEI_LIVE_REFRESH_HREF = "/assets/appsVeiLiveRefresh-B1aRNyzk.js";
