// Auto-generated by `asset-hrefs-plugin.ts` right after `vite build --outDir dist/client` finishes - do not edit by hand.
export const GLOBALS_CSS_HREF = "/assets/appsGlobals-ecF1hu8k.css";
export const HYDRATE_ENTRY_HREF = "/assets/appsHydrate-DjHpNDRx.js";
export const VEI_OVERLAY_HREF = "/assets/appsVeiOverlay-CM0ckW89.js";
export const HYDRATE_BUILT_HREF = "/assets/appsHydrateBuilt-CxuIf1WE.js";
