// Auto-generated by `asset-hrefs-plugin.ts` right after `vite build --outDir dist/client` finishes - do not edit by hand.
export const GLOBALS_CSS_HREF = "/assets/appsGlobals-CBFvtpzl.css";
export const HYDRATE_ENTRY_HREF = "/assets/appsHydrate-CJtiVILR.js";
export const VEI_OVERLAY_HREF = "/assets/appsVeiOverlay-CbGbd8cE.js";
