// Generated by `src/content-types/codegen.ts` (`bun run dry:generate`, and
// once on dev-server startup) - do not edit by hand. Re-run after changing a
// content type's schema; see plans/reader.md.
//
// Calling the ambient globals `dry()`/`params()`/`setTitle()` below works for
// free in any file under `src/apps/pages/**` -
// `src/server/app-router/app-router-plugin.ts` (registered in
// `vite.config.ts`) injects the real import automatically. Outside that
// folder, import them yourself instead:
// `import { dry } from "../content-types/dry-reader.js"`,
// `import { params } from "../content-types/params-reader.js"`,
// `import { setTitle } from "../content-types/dry-title.js"`.

import type { DryReader } from "../content-types/dry-reader.js";

export interface User {
  id: number;
  name: string;
  email: string;
  roles?: number[]; // relation -> role
  createdAt?: Date;
  updatedAt?: Date;
  memory?: number[]; // relationmirror -> memory, read-only
}

export interface Menu {
  id: number;
  name: string;
  refs: MenuItem[];
  createdAt?: Date;
  updatedAt?: Date;
}

export interface AiKey {
  id: number;
  name: string;
  description?: string;
  provider: "Google" | "Anthropic" | "ChatGPT" | "Custom";
  model: string[];
  url?: string;
  sortIndex?: number;
}

export interface Role {
  id: number;
  name: string;
  description?: string;
  isSuperAdmin?: boolean;
  permissions?: string[];
  user?: number[]; // relationmirror -> user, read-only
}

export interface Redirect {
  id: number;
  from: string;
  to: string;
}

export interface Memory {
  id: number;
  user: number | null; // relation -> user
  data?: string;
  version: number;
}

export interface Blog {
  id: number;
  title: string;
  slug: string;
  noiDung?: string;
}

export interface Category {
  id: number;
  title: string;
  slug: string;
}

export interface SeoDefaults {
  id: number;
  seo: Seo;
}

export interface SystemSettings {
  id: number;
  data?: string;
}

export interface GoogleVerification {
  id: number;
  name: string;
  content: string;
}

export interface Config {
  id: number;
  description?: string;
  title: string;
  slug: string;
}

export interface GithubSync {
  id: number;
  enabled?: boolean;
  repo: string;
  branch: string;
}

export interface Homepage {
  id: number;
  hero: HeroSection;
  valueProps: ValueProp[];
  videoSection: VideoSection;
  latestPostsSection: LatestPostsSection;
  pressSection: PressSection;
  pressMentions: PressMention[];
  bottomCta: BottomCta;
  seo: Seo;
}

export interface About {
  id: number;
  intro: AboutIntro;
  story: AboutStory;
  missionSection: AboutMissionSection;
  missionItems: MissionItem[];
  experienceSection: AboutExperienceSection;
  experienceItems: ExperienceItem[];
  pressSection: AboutPressSection;
  pressMentions: PressMention[];
  bottomCta: BottomCta;
  seo: Seo;
}

export interface Contact {
  id: number;
  header: ContactHeader;
  channels: ContactChannel[];
  seo: Seo;
}

export interface SiteSettings {
  id: number;
  brandName: string;
  headerCtaLabel?: string;
  headerCtaHref?: string;
  footerDescription?: string;
  phone?: string;
  email?: string;
  fanpageUrl?: string;
  copyrightText?: string;
}

export interface BlogsPage {
  id: number;
  header: BlogsHeader;
  bottomCta: BottomCta;
  seo: Seo;
}

export interface MenuItem {
  label: string;
  description?: string;
  href: string;
}

export interface Seo {
  metaTitle?: string;
  description?: string;
  image?: string;
  noIndex?: boolean;
}

export interface HeroSection {
  eyebrow: string;
  headline: string;
  subtitle: string;
  content?: string;
  image: string;
}

export interface ValueProp {
  headline: string;
  description: string;
}

export interface VideoSection {
  videoUrl: string;
  heading: string;
  description?: string;
  ctaLabel?: string;
  ctaHref?: string;
}

export interface LatestPostsSection {
  heading: string;
  viewAllHref?: string;
}

export interface PressSection {
  heading: string;
  viewAllHref?: string;
}

export interface PressMention {
  outlet: string;
  headline: string;
  date: string;
  href?: string;
  image?: string;
}

export interface BottomCta {
  heading: string;
  description?: string;
  ctaLabel?: string;
  ctaHref?: string;
}

export interface AboutIntro {
  eyebrow: string;
  headline: string;
  description: string;
  image: string;
}

export interface AboutStory {
  heading: string;
  content: string;
}

export interface AboutMissionSection {
  heading: string;
}

export interface MissionItem {
  text: string;
}

export interface AboutExperienceSection {
  heading: string;
}

export interface ExperienceItem {
  year: string;
  description: string;
}

export interface AboutPressSection {
  heading: string;
  description?: string;
}

export interface ContactHeader {
  eyebrow: string;
  headline: string;
  description?: string;
}

export interface ContactChannel {
  kind: "phone" | "email" | "fanpage";
  label: string;
  value: string;
  href: string;
}

export interface BlogsHeader {
  eyebrow: string;
  headline: string;
  description?: string;
}

export interface UserRelations {
  roles: Role[];
  memory: Memory[];
}

export interface MenuRelations {}

export interface AiKeyRelations {}

export interface RoleRelations {
  user: User[];
}

export interface RedirectRelations {}

export interface MemoryRelations {
  user: User | null;
}

export interface BlogRelations {}

export interface CategoryRelations {}

export interface SeoDefaultsRelations {}

export interface SystemSettingsRelations {}

export interface GoogleVerificationRelations {}

export interface ConfigRelations {}

export interface GithubSyncRelations {}

export interface HomepageRelations {}

export interface AboutRelations {}

export interface ContactRelations {}

export interface SiteSettingsRelations {}

export interface BlogsPageRelations {}

export type DryCollectionName = "user" | "menu" | "aiKey" | "role" | "redirect" | "memory" | "blog" | "category";
export type DrySingletonName = "seoDefaults" | "systemSettings" | "googleVerification" | "config" | "githubSync" | "homepage" | "about" | "contact" | "siteSettings" | "blogsPage";

export interface DryCollectionMap {
  "user": User;
  "menu": Menu;
  "aiKey": AiKey;
  "role": Role;
  "redirect": Redirect;
  "memory": Memory;
  "blog": Blog;
  "category": Category;
}

export interface DrySingletonMap {
  "seoDefaults": SeoDefaults;
  "systemSettings": SystemSettings;
  "googleVerification": GoogleVerification;
  "config": Config;
  "githubSync": GithubSync;
  "homepage": Homepage;
  "about": About;
  "contact": Contact;
  "siteSettings": SiteSettings;
  "blogsPage": BlogsPage;
}

export interface DryCollectionRelationsMap {
  "user": UserRelations;
  "menu": MenuRelations;
  "aiKey": AiKeyRelations;
  "role": RoleRelations;
  "redirect": RedirectRelations;
  "memory": MemoryRelations;
  "blog": BlogRelations;
  "category": CategoryRelations;
}

export interface DrySingletonRelationsMap {
  "seoDefaults": SeoDefaultsRelations;
  "systemSettings": SystemSettingsRelations;
  "googleVerification": GoogleVerificationRelations;
  "config": ConfigRelations;
  "githubSync": GithubSyncRelations;
  "homepage": HomepageRelations;
  "about": AboutRelations;
  "contact": ContactRelations;
  "siteSettings": SiteSettingsRelations;
  "blogsPage": BlogsPageRelations;
}

declare global {
  function dry(): DryReader<DryCollectionMap, DrySingletonMap, DryCollectionRelationsMap, DrySingletonRelationsMap>;
  /** The matched route's dynamic segments - `[slug]` -> `string`,
   * `[...path]` -> `string[]`. Same value a page/layout receives as its
   * `params` prop, readable from any helper function too. */
  function params(): Record<string, string | string[]>;
  /** Sets this page's `<title>`/`og:title`, overriding every SEO cascade
   * layer (see `dry-seo.ts`). Last call wins. */
  function setTitle(title: string): void;
  /** Marks an element as the editable source of one field, for the Visual
   * Editing Interface (`plans/vei.md`):
   * `<h1 {...dryBind(post.$.title)}>{post.title}</h1>`, or
   * `<img {...dryBind(post.$.hero, "src")} src={imageUrl(post.hero)} />`.
   * Emits nothing at all outside edit mode. */
  function dryBind(value: unknown, attribute?: string): Record<string, string>;
}
