// Generated by `src/content-types/codegen.ts` (`bun run dry:generate`, and
// once on dev-server startup) - do not edit by hand. Re-run after changing a
// content type's schema; see plans/reader.md.
//
// Calling the ambient global `dry()` below works for free in any file under
// `src/apps/pages/**` - `src/server/app-router/dry-global-plugin.ts`
// (registered in `vite.config.ts`) injects the real import automatically.
// Outside that folder, import it yourself instead:
// `import { dry } from "../content-types/dry-reader.js"`.

import type { DryReader } from "../content-types/dry-reader.js";

export interface User {
  id: number;
  name: string;
  email: string;
  roles?: number[]; // relation -> role
  createdAt?: Date;
  updatedAt?: Date;
  content?: string;
}

export interface Menu {
  id: number;
  name: string;
  refs: MenuItem[];
  createdAt?: Date;
  updatedAt?: Date;
}

export interface AiKey {
  id: number;
  name: string;
  description?: string;
  provider: "Google" | "Anthropic" | "ChatGPT" | "Custom";
  model: string;
  url?: string;
  sortIndex?: number;
}

export interface Role {
  id: number;
  name: string;
  description?: string;
  isSuperAdmin?: boolean;
  permissions?: string[];
  user?: number[]; // relationmirror -> user, read-only
}

export interface MenuItem {
  label: string;
  description?: string;
  href: string;
}

export interface Seo {
  metaTitle?: string;
  description?: string;
  image?: string;
}

export type DryCollectionName = "user" | "menu" | "aiKey" | "role";
export type DrySingletonName = never;

export interface DryCollectionMap {
  "user": User;
  "menu": Menu;
  "aiKey": AiKey;
  "role": Role;
}

export interface DrySingletonMap {

}

declare global {
  function dry(): DryReader<DryCollectionMap, DrySingletonMap>;
}
