/**
 * Pre-builds `preact-runtime.js` (`apps/build-preact-runtime-bundle.ts`) and
 * writes it into `generated-preact-runtime.ts` as a plain string constant -
 * see that file's own doc comment, and `built-pages-storage.ts`'s
 * `ensurePreactRuntimeAsset`, for why a Workers deployment needs this: it
 * can never run the nested `vite.build()` this bundle needs itself
 * (workerd has no Vite/Node tooling), so without a build-time-baked fallback
 * its very first request for this asset had nothing to serve and had to
 * refuse outright (found live, 2026-08-13 - a fresh/recreated R2 bucket has
 * no cached copy either).
 *
 * Run with: bun run build:worker (chained between the client build and the
 * SSR build - the SSR build's `entry-worker.ts` imports this generated
 * file, so it must be fresh before that build starts). Not chained into
 * plain `bun run build` (the Node target): `ensurePreactRuntimeAsset`
 * self-bootstraps live there instead (`isNodeRuntime()`), so the committed
 * fallback never actually gets read on that path - regenerating it there
 * too would just be unused work.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { buildPreactRuntimeBundle } from "../src/apps/build-preact-runtime-bundle.js";

const code = await buildPreactRuntimeBundle();
const target = fileURLToPath(new URL("../src/server/app-router/generated-preact-runtime.ts", import.meta.url));
const header = "// Auto-generated by `scripts/build-preact-runtime.ts` - do not edit by hand.\n";
await writeFile(target, `${header}export const PREACT_RUNTIME_JS = ${JSON.stringify(code)};\n`);
console.log(`[drycms] wrote generated-preact-runtime.ts (${code.length} bytes)`);
