/**
 * Generates `src/components/icons.tsx` from `icons.config.json`.
 *
 * Icons are inlined at build time so the published package carries no icon
 * dependency and the browser makes no request to the Iconify API. Each icon is
 * a separate named export, so bundlers drop the ones an app does not use.
 *
 * Run with: bun run build:icons
 */
import { createRequire } from "node:module";
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { getIconData, iconToSVG } from "@iconify/utils";

const require = createRequire(import.meta.url);
const root = new URL("../", import.meta.url);

/** Preference order: Solar first, then Lucide. */
const SETS = ["solar", "lucide"];

const config = require("../icons.config.json");
const collections = new Map(
  SETS.map((prefix) => [prefix, require(`@iconify-json/${prefix}/icons.json`)]),
);

function render(source) {
  if (typeof source === "object" && source !== null) {
    return source;
  }

  const id = source;
  const [prefix, name] = id.split(":");
  if (!prefix || !name) {
    throw new Error(`Icon "${id}" must be written as "<set>:<name>".`);
  }
  if (!SETS.includes(prefix)) {
    throw new Error(
      `Icon "${id}" uses set "${prefix}"; allowed sets are ${SETS.join(", ")}.`,
    );
  }

  const collection = collections.get(prefix);
  const data = getIconData(collection, name);
  if (!data) {
    throw new Error(`Icon "${id}" does not exist in @iconify-json/${prefix}.`);
  }

  const { attributes, body } = iconToSVG(data, { height: "auto" });
  return { viewBox: attributes.viewBox, body };
}

const DEFAULT_VIEW_BOX = "0 0 24 24";

const entries = Object.entries(config.icons).filter(
  ([key]) => !key.startsWith("$"),
);
const rendered = entries.map(([key, source]) => ({
  key,
  id: typeof source === "string" ? source : "custom SVG",
  ...render(source),
}));

function iconEntry(icon) {
  return icon.viewBox === DEFAULT_VIEW_BOX
    ? `icon(${JSON.stringify(icon.body)})`
    : `icon(${JSON.stringify(icon.body)}, ${JSON.stringify(icon.viewBox)})`;
}

const parts = [
  "// Generated by scripts/build-icons.mjs - do not edit.",
  "// Source: Iconify (Solar, Lucide). Run `bun run build:icons` to regenerate.",
  "",
  "import type { JSX } from 'preact';",
  "",
  "export type IconProps = Omit<JSX.SVGAttributes<SVGSVGElement>, 'viewBox' | 'children'>;",
  "",
  `const DEFAULT_VIEW_BOX = ${JSON.stringify(DEFAULT_VIEW_BOX)};`,
  "",
  "interface IconEntry {",
  "\tbody: string;",
  "\tviewBox?: string;",
  "}",
  "",
  "function icon(body: string, viewBox?: string): IconEntry {",
  "\treturn viewBox ? { body, viewBox } : { body };",
  "}",
  "",
  "/** Raw `<svg>` inner markup (+ `viewBox` when it isn't the 24x24 default), for consumers that render it via `dangerouslySetInnerHTML`. */",
  "export const iconBodies = {",
  ...rendered.map((icon) => `\t${icon.key}: ${iconEntry(icon)},`),
  "} as const;",
  "",
  "export type IconName = keyof typeof iconBodies;",
  "",
];

for (const icon of rendered) {
  parts.push(
    `/** \`${icon.id}\` */`,
    `export function ${icon.key}Icon(props: IconProps) {`,
    "\treturn (",
    `\t\t<svg viewBox={iconBodies.${icon.key}.viewBox ?? DEFAULT_VIEW_BOX} width="1em" height="1em" aria-hidden="true" {...props} dangerouslySetInnerHTML={{ __html: iconBodies.${icon.key}.body }} />`,
    "\t);",
    "}",
    "",
  );
}

const target = new URL("src/components/icons.tsx", root);
writeFileSync(fileURLToPath(target), parts.join("\n"));

console.log(`Generated ${rendered.length} icons -> ${fileURLToPath(target)}`);
