/**
 * Zips this tenant's own `src/apps/<root>/**` (whatever `sync-pages-r2.ts
 * --pull` last materialized from `pagesSourceStorage` - real content, not a
 * generic starter) and writes it into `generated-pages-source-seed.ts` as a
 * base64 string constant - the same "bake build-time data into a committed
 * .ts file, since a Worker has no filesystem to read from at runtime"
 * precedent `build-preact-runtime.ts` already established for
 * `generated-preact-runtime.ts`.
 *
 * `src/server/pages-source-seed.ts` reads this constant to seed a fresh
 * tenant's REAL R2 bucket on its first production request, replacing what's
 * documented (`AGENTS.md`) as a manual `bun run pages:sync --push --remote`
 * step today.
 *
 * Run with: bun run build:worker (chained between the client build and the
 * SSR build, same slot `build-preact-runtime.ts` occupies - the SSR build's
 * `entry-worker.ts` imports this generated file transitively, so it must be
 * fresh before that build starts). Not chained into plain `bun run build`
 * (the Node target): `pagesSourceStorage` there is always real local disk
 * already, nothing to seed.
 */
import { readdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { buildZip, type ZipEntryInput } from "../src/storage/zip.js";
import { base64Encode } from "../src/lib/secret-crypto.js";
import { PAGES_SOURCE_ROOTS } from "../src/server/app-router/source-roots.js";

const GIT_APPS_ROOT = fileURLToPath(new URL("../src/apps/", import.meta.url)).replace(/\/$/, "");
const TARGET = fileURLToPath(new URL("../src/server/generated-pages-source-seed.ts", import.meta.url));

async function filesUnder(dir: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return [];
  }
  const found: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await filesUnder(full)));
    else if (entry.isFile() && entry.name !== ".dir") found.push(full);
  }
  return found;
}

const zipEntries: ZipEntryInput[] = [];
for (const root of PAGES_SOURCE_ROOTS) {
  const rootDir = join(GIT_APPS_ROOT, root.id);
  for (const file of await filesUnder(rootDir)) {
    const relPath = file.slice(GIT_APPS_ROOT.length + 1).split("\\").join("/");
    zipEntries.push({ path: relPath, data: await readFile(file) });
  }
}

// `src/apps/pages` is disposable (gitignored, "safe to delete locally at any
// time" per AGENTS.md) and reads empty right after `.wrangler` is wiped or on
// a fresh checkout that never ran a `--pull` yet. Regenerating the constant
// to "" in that moment would silently clobber the real, committed default
// seed (baked from an earlier commit's real content) with an empty one -
// permanently breaking `ensurePagesSourceSeeded` for every tenant bootstrapped
// off this build until someone notices and manually restores it. Skip the
// write entirely instead, leaving whatever's already committed in place.
if (zipEntries.length === 0) {
  console.log("[drycms] no files under src/apps/{pages,component,styles,md} - leaving generated-pages-source-seed.ts untouched.");
} else {
  const base64 = base64Encode(buildZip(zipEntries));
  const header = "// Auto-generated by `scripts/build-pages-source-seed.ts` - do not edit by hand.\n";
  await writeFile(TARGET, `${header}export const PAGES_SOURCE_SEED_ZIP_BASE64 = ${JSON.stringify(base64)};\n`);
  console.log(`[drycms] wrote generated-pages-source-seed.ts (${zipEntries.length} file(s), ${base64.length} base64 chars)`);
}
