/**
 * Generates `content-types/engine/fresh-boot-dump.generated.ts` - the "fresh
 * boot" schema+seed SQL dump `routes/full-reset.ts`'s D1 path restores onto
 * the real database. A Cloudflare Worker has no `bun:sqlite`/`node:sqlite`/
 * `better-sqlite3` to build this dump live at request time the way the local
 * sqlite content engine does (`sqlite-driver.ts`'s `resolveSqliteDriver` has
 * no Workers-compatible path at all), so it's produced here instead, ahead
 * of time, by a script that runs under bun/node (this one) - chained into
 * `build:worker` (`package.json`) so it's regenerated on every Workers
 * build and can never silently drift from `bootstrapDefaultContentSchema`'s
 * real seed/schema logic. The local-sqlite content engine keeps building its
 * own copy live, unchanged - it already has a real driver at request time.
 *
 * Run with: bun run build:worker, or standalone via
 * `bun scripts/build-fresh-boot-dump.ts`.
 */
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { resolveSqliteDriver } from "../src/content-types/engine/sqlite-driver.js";
import { bootstrapDefaultContentSchema } from "../src/content-types/engine/sqlite.js";
import { buildSqlDump, sqliteRawHandle } from "../src/content-types/engine/backup.js";

const scratch = await resolveSqliteDriver(":memory:");
bootstrapDefaultContentSchema(scratch);
const superAdminRoleId = scratch.all<{ id: number }>(`SELECT "id" FROM "role" WHERE "name" = 'Super Admin';`)[0]?.id;
if (superAdminRoleId === undefined) {
  throw new Error("[drycms] fresh-boot bootstrap produced no Super Admin role - aborting dump generation.");
}
const dump = await buildSqlDump(sqliteRawHandle(scratch));

// `resetContent` re-inserts the live `githubSync`/`systemSettings` singleton
// rows onto this fresh schema verbatim - a live tenant's table can carry
// columns the current built-in default definition (`seed.ts`) no longer
// has (schema drift, same category as `status/`'s "seed vs live DB" note),
// so it needs each table's REAL fresh-boot column set to filter against
// rather than trusting the live row's own columns blindly.
function tableColumns(table: string): string[] {
  return scratch.all<{ name: string }>(`PRAGMA table_info(${JSON.stringify(table)});`).map((row) => row.name);
}
const githubSyncColumns = tableColumns("githubSync");
const systemSettingsColumns = tableColumns("systemSettings");

const target = fileURLToPath(new URL("../src/content-types/engine/fresh-boot-dump.generated.ts", import.meta.url));
const contents =
  `// Generated by scripts/build-fresh-boot-dump.ts - do not edit by hand.\n` +
  `// Regenerated on every "bun run build:worker" so it can never drift from\n` +
  `// bootstrapDefaultContentSchema's real seed/schema logic. See that\n` +
  `// script's own doc comment, and routes/full-reset.ts's D1 usage.\n\n` +
  `export const FRESH_BOOT_DUMP = ${JSON.stringify(dump)};\n\n` +
  `export const FRESH_BOOT_SUPER_ADMIN_ROLE_ID = ${JSON.stringify(superAdminRoleId)};\n\n` +
  `export const FRESH_BOOT_GITHUB_SYNC_COLUMNS = ${JSON.stringify(githubSyncColumns)};\n\n` +
  `export const FRESH_BOOT_SYSTEM_SETTINGS_COLUMNS = ${JSON.stringify(systemSettingsColumns)};\n`;

await writeFile(target, contents, "utf8");
console.log(`[drycms] generated fresh-boot-dump.generated.ts (${dump.length} bytes dump, super admin role id ${superAdminRoleId})`);
