import { describe, expect, it } from "vitest";
import { loadTailwindCompletionSnapshot, tailwindCompletionSource } from "./tailwind-completions.js";

function labelsFor(snapshot: Awaited<ReturnType<typeof loadTailwindCompletionSnapshot>>, before: string): string[] {
  const result = tailwindCompletionSource(
    {
      before,
      after: "",
      pos: before.length,
      explicit: false,
    },
    snapshot,
  );
  return result?.options.map((option) => option.label) ?? [];
}

describe("project Tailwind completions", () => {
  it("includes utilities generated by the project's custom theme tokens", async () => {
    const snapshot = await loadTailwindCompletionSnapshot(`
      @import "tailwindcss";
      @theme inline {
        --color-muted: oklch(0.97 0 0);
        --color-muted-foreground: oklch(0.556 0 0);
      }
    `);

    expect(snapshot.classList).toContain("bg-muted");
    expect(snapshot.classList).toContain("text-muted-foreground");
    expect(labelsFor(snapshot, 'class="bg-mu')).toContain("bg-muted");
    expect(labelsFor(snapshot, 'class="text-muted-f')).toContain("text-muted-foreground");
  });

  it("keeps snapshots for different project themes isolated", async () => {
    const [brand, campaign] = await Promise.all([
      loadTailwindCompletionSnapshot('@import "tailwindcss"; @theme { --color-brand: red; }'),
      loadTailwindCompletionSnapshot('@import "tailwindcss"; @theme { --color-campaign: blue; }'),
    ]);

    expect(brand.classList).toContain("bg-brand");
    expect(brand.classList).not.toContain("bg-campaign");
    expect(campaign.classList).toContain("bg-campaign");
    expect(campaign.classList).not.toContain("bg-brand");
  });

  it("rejects unresolved project imports instead of silently returning a partial theme", async () => {
    await expect(loadTailwindCompletionSnapshot('@import "tailwindcss"; @import "./missing.css";')).rejects.toThrow(
      'Unsupported Tailwind stylesheet import "./missing.css"',
    );
  });
});
